### ISSUE TITLE
Nullish coalescing operator

### ISSUE THREAD

**Issue by UnleashedMySelf** [caneara/iodine#56]
Hi, we have a problem on old iphones (ios 12/13 at least), can we somehow replace nullish coalescing operator on 101 line?
Thanks!
![image](https://github.com/caneara/iodine/assets/25558430/28190f3e-4393-42ca-be36-9e44576743e0)

**Comment by mattkingshott** [comment]
Given this issue relates to an old OS (2018), I won't be addressing it myself. However, I'll review a PR if you want to send one.

**Comment by UnleashedMySelf** [comment]
@mattkingshott 
just replace it with ||
or convert nullish coalescing operator to es5 format
